# Generated by Django 5.2.1 on 2026-08-08 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SapDocumentDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("delivery", "Delivery"), ("pickup", "Pickup")],
                        max_length=10,
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        help_text="Source challan number, e.g. DC-000101",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("card_code", models.CharField(blank=True, default="", max_length=20)),
                ("card_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "from_warehouse",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("from_gstin", models.CharField(blank=True, default="", max_length=15)),
                ("from_state_code", models.IntegerField(blank=True, null=True)),
                ("from_pincode", models.IntegerField(blank=True, null=True)),
                ("from_address", models.TextField(blank=True, default="")),
                (
                    "to_warehouse",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("to_gstin", models.CharField(blank=True, default="", max_length=15)),
                ("to_state_code", models.IntegerField(blank=True, null=True)),
                ("to_pincode", models.IntegerField(blank=True, null=True)),
                ("to_address", models.TextField(blank=True, default="")),
                (
                    "vehicle_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "transport_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Road", "Road"),
                            ("Rail", "Rail"),
                            ("Air", "Air"),
                            ("Ship", "Ship"),
                        ],
                        default="Road",
                        max_length=10,
                    ),
                ),
                (
                    "transporter_id",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("distance_km", models.IntegerField(blank=True, null=True)),
                ("posting_date", models.DateField()),
                ("comments", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "SAP Document Draft",
                "verbose_name_plural": "SAP Document Drafts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DraftLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_num", models.IntegerField(default=0)),
                ("item_code", models.CharField(max_length=50)),
                ("item_name", models.CharField(blank=True, default="", max_length=255)),
                ("hsn_code", models.CharField(blank=True, default="", max_length=10)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(default="NOS", max_length=10)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sap_builder.sapdocumentdraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Draft Line",
                "verbose_name_plural": "Draft Lines",
                "ordering": ["line_num", "id"],
            },
        ),
        migrations.CreateModel(
            name="BuiltPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "builder_used",
                    models.CharField(
                        help_text="Builder class that produced this payload",
                        max_length=100,
                    ),
                ),
                (
                    "recipe",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Director recipe name, if a director built it",
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("line_count", models.IntegerField(default=0)),
                (
                    "taxable_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cgst_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "sgst_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "igst_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("built_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="built_payloads",
                        to="sap_builder.sapdocumentdraft",
                    ),
                ),
            ],
            options={
                "verbose_name": "Built Payload",
                "verbose_name_plural": "Built Payloads",
                "ordering": ["-built_at"],
            },
        ),
    ]
