# Generated by Django 5.2.1 on 2026-08-06 22:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sap_ref",
                    models.CharField(
                        blank=True,
                        help_text="SAP Customer Reference Number (synced from SAP B1)",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        help_text="Registered company name", max_length=255
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "gstn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="GST Identification Number",
                        max_length=20,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Credit limit in INR",
                        max_digits=12,
                    ),
                ),
                (
                    "credit_rating",
                    models.CharField(
                        choices=[
                            ("A", "Excellent"),
                            ("B", "Good"),
                            ("C", "Average"),
                            ("D", "Poor"),
                            ("E", "Blocked"),
                        ],
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "due_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Payment due days"
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("construction", "Construction"),
                            ("infrastructure", "Infrastructure"),
                            ("industrial", "Industrial"),
                            ("events", "Events"),
                        ],
                        default="construction",
                        max_length=20,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="KYC verification status"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("purchaser", "Purchaser"),
                            ("site_contact", "Site Contact"),
                            ("decision_maker", "Decision Maker"),
                        ],
                        default="purchaser",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["contact_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="CustomerOutstanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original invoice amount in INR",
                        max_digits=12,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Remaining balance in INR",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("partial", "Partially Paid"),
                            ("overdue", "Overdue"),
                            ("paid", "Paid"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outstandings",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
    ]
