# Generated by Django 5.2.1 on 2026-08-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challan_no", models.CharField(max_length=50, unique=True)),
                (
                    "challan_type",
                    models.CharField(
                        choices=[("Delivery", "Delivery"), ("Pickup", "Pickup")],
                        max_length=20,
                    ),
                ),
                (
                    "challan_movement_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery"),
                            ("pickup", "Pickup"),
                            ("inter_branch", "Inter Branch"),
                            ("capital_purchase", "Capital Purchase"),
                            ("sales", "Sales"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order_id", models.IntegerField(blank=True, null=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("pickup_location", models.CharField(default="", max_length=255)),
                ("delivery_location", models.CharField(default="", max_length=255)),
                ("dispatch_date", models.DateField(blank=True, null=True)),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "vehicle_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "is_authorized",
                    models.CharField(
                        choices=[
                            ("0", "Pending"),
                            ("1", "Authorized"),
                            ("-1", "Rejected"),
                        ],
                        default="0",
                        max_length=2,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(default="PLANNING_DONE", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChallanCreationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement_type", models.CharField(max_length=20)),
                ("required_fields_validated", models.JSONField()),
                ("factory_used", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creation_logs",
                        to="challans.challan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChallanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=50)),
                ("item_name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("ok_quantity", models.IntegerField(default=0)),
                ("damaged_quantity", models.IntegerField(default=0)),
                (
                    "challan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="challans.challan",
                    ),
                ),
            ],
        ),
    ]
