# Generated by Django 5.2.1 on 2026-08-08 14:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challan_no", models.CharField(max_length=20, unique=True)),
                (
                    "challan_type",
                    models.CharField(
                        choices=[("Delivery", "Delivery"), ("Pickup", "Pickup")],
                        max_length=10,
                    ),
                ),
                (
                    "challan_movement_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery"),
                            ("pickup", "Pickup"),
                            ("inter_branch", "Inter Branch"),
                            ("sales", "Sales"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order_id", models.IntegerField()),
                ("pickup_location", models.CharField(max_length=255)),
                ("delivery_location", models.CharField(max_length=255)),
                ("dispatch_date", models.DateField(blank=True, null=True)),
                (
                    "is_authorized",
                    models.CharField(
                        choices=[
                            ("0", "Under Review"),
                            ("1", "Authorized"),
                            ("-1", "Rejected"),
                        ],
                        default="0",
                        max_length=2,
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("PLANNING_DONE", "Planning Done"),
                            ("GENERATED_CHALLAN", "Generated Challan"),
                            ("VEHICLE_EXIT", "Vehicle Exit"),
                            ("ARRIVAL_AT_SITE", "Arrival At Site"),
                            ("INSTALLATION_DONE", "Installation Done"),
                            ("SITE_EXIT", "Site Exit"),
                            ("ARRIVAL_AT_BRANCH", "Arrival At Branch"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PLANNING_DONE",
                        max_length=30,
                    ),
                ),
                (
                    "freight_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Challans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChallanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=50)),
                ("item_name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("ok_quantity", models.IntegerField(default=0)),
                ("damaged_quantity", models.IntegerField(default=0)),
                ("missing_quantity", models.IntegerField(default=0)),
                (
                    "challan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="challan_management.challan",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ChallanStageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_stage", models.CharField(max_length=30)),
                ("to_stage", models.CharField(max_length=30)),
                ("changed_by", models.CharField(blank=True, max_length=100, null=True)),
                ("remarks", models.TextField(blank=True, default="")),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stage_logs",
                        to="challan_management.challan",
                    ),
                ),
            ],
            options={
                "ordering": ["changed_at"],
            },
        ),
    ]
