# Generated by Django 5.2.1 on 2026-08-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SapConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_url", models.URLField()),
                ("session_id", models.CharField(max_length=255)),
                (
                    "company_db",
                    models.CharField(default="YOUNGMAN_LIVE", max_length=100),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("request_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="ConnectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("Invoices", "Invoices"),
                            ("CreditNotes", "Credit Notes"),
                            ("JournalEntries", "Journal Entries"),
                            ("BusinessPartners", "Business Partners"),
                            ("Orders", "Orders"),
                            ("Session", "Session"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("POST", "POST"), ("GET", "GET"), ("PATCH", "PATCH")],
                        max_length=20,
                    ),
                ),
                ("endpoint", models.CharField(max_length=200)),
                ("success", models.BooleanField(default=True)),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="sap_connector.sapconnection",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
