# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x07userlab\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"%\n\x10ListUsersRequest\x12\x11\n\tpage_size\x18\x01 \x01(\x05\x32\xb2\x01\n\x0bUserService\x12\x31\n\x07GetUser\x12\x17.userlab.GetUserRequest\x1a\r.userlab.User\x12\x37\n\nCreateUser\x12\x1a.userlab.CreateUserRequest\x1a\r.userlab.User\x12\x37\n\tListUsers\x12\x19.userlab.ListUsersRequest\x1a\r.userlab.User0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=31
  _globals['_USER']._serialized_end=78
  _globals['_GETUSERREQUEST']._serialized_start=80
  _globals['_GETUSERREQUEST']._serialized_end=108
  _globals['_CREATEUSERREQUEST']._serialized_start=110
  _globals['_CREATEUSERREQUEST']._serialized_end=158
  _globals['_LISTUSERSREQUEST']._serialized_start=160
  _globals['_LISTUSERSREQUEST']._serialized_end=197
  _globals['_USERSERVICE']._serialized_start=200
  _globals['_USERSERVICE']._serialized_end=378
# @@protoc_insertion_point(module_scope)
