# Generated by Django 5.2.1 on 2026-08-06 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditPipelineEntry",
            fields=[
                (
                    "invoice_doc_number",
                    models.CharField(
                        help_text="Unique invoice document number, e.g. INV-2025-0001",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_id", models.IntegerField(help_text="Youngman Sales Order ID")),
                (
                    "customer_name",
                    models.CharField(
                        help_text="Customer / debtor name", max_length=255
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date the invoice was created"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original invoice amount",
                        max_digits=12,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, help_text="Outstanding balance", max_digits=12
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("BILL_MADE", "Bill Made"),
                            ("BILL_SUBMITTED", "Bill Submitted"),
                            ("BILL_BOOKED", "Bill Booked"),
                            ("BILL_OVERDUE", "Bill Overdue"),
                            ("FIRST_PTP", "First PTP"),
                            ("SECOND_PTP", "Second PTP"),
                            ("THIRD_PTP", "Third PTP"),
                            ("FORCE_PICKUP", "Force Pickup"),
                            ("SALES_ISSUE", "Sales Issue"),
                            ("LEGAL", "Legal"),
                            ("BAD_DEBT", "Bad Debt"),
                            ("BILL_PAID", "Bill Paid"),
                        ],
                        default="BILL_MADE",
                        help_text="Current state in the credit pipeline",
                        max_length=30,
                    ),
                ),
                (
                    "current_remarks",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Latest remarks / notes on the entry",
                    ),
                ),
                (
                    "ptp_date",
                    models.DateField(
                        blank=True,
                        help_text="Promise-to-pay date (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Payment due date", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Record creation timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Pipeline Entry",
                "verbose_name_plural": "Credit Pipeline Entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransitionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        help_text="State before the transition", max_length=30
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        help_text="State after the transition", max_length=30
                    ),
                ),
                (
                    "command_name",
                    models.CharField(
                        help_text="Name of the Command that triggered this transition",
                        max_length=50,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Remarks / reason for the transition",
                    ),
                ),
                (
                    "executed_by",
                    models.CharField(
                        default="system",
                        help_text="User or system that executed the command",
                        max_length=100,
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of execution"
                    ),
                ),
                (
                    "is_undone",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this transition was later undone",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        help_text="The pipeline entry this transition belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="credit_pipeline.creditpipelineentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transition Log",
                "verbose_name_plural": "Transition Logs",
                "ordering": ["-executed_at"],
            },
        ),
    ]
