# Generated by Django 5.2.1 on 2026-08-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("credit_pipeline", "Credit Pipeline"),
                            ("challan_tat", "Challan TAT"),
                            ("revenue", "Revenue"),
                            ("utilization", "Utilization"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "output_format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("excel", "Excel"), ("json", "JSON")],
                        default="csv",
                        max_length=10,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_generated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_content", models.TextField()),
                ("row_count", models.IntegerField(default=0)),
                ("column_count", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("sent_to", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="generated",
                        max_length=20,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "unique_together": {("report", "email")},
            },
        ),
    ]
