# Generated by Django 5.2.1 on 2026-08-08 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SapDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_family",
                    models.CharField(
                        choices=[
                            ("delivery", "Delivery Note"),
                            ("return", "Return"),
                            ("transfer", "Inventory Transfer"),
                            ("invoice", "A/R Invoice"),
                        ],
                        help_text="Which SAP document family this record becomes",
                        max_length=20,
                    ),
                ),
                (
                    "reference_no",
                    models.CharField(
                        help_text="Source document number in Aandhi, e.g. DC-000101",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "card_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SAP Business Partner code. Blank for internal transfers.",
                        max_length=20,
                    ),
                ),
                (
                    "card_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Business partner name, for readability only",
                        max_length=255,
                    ),
                ),
                (
                    "from_warehouse",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Issuing warehouse code",
                        max_length=20,
                    ),
                ),
                (
                    "to_warehouse",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Receiving warehouse code (inventory transfers)",
                        max_length=20,
                    ),
                ),
                ("posting_date", models.DateField(help_text="SAP DocDate")),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text comments carried into SAP",
                    ),
                ),
                (
                    "doc_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Document total, used by the invoice family",
                        max_digits=14,
                    ),
                ),
                (
                    "return_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Why material came back (return family only)",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        help_text="Posting status",
                        max_length=10,
                    ),
                ),
                (
                    "sap_doc_entry",
                    models.IntegerField(
                        blank=True,
                        help_text="DocEntry assigned by SAP once posted",
                        null=True,
                    ),
                ),
                (
                    "sap_doc_num",
                    models.IntegerField(
                        blank=True,
                        help_text="Human-facing DocNum assigned by SAP",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="Last posting failure reason"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "SAP Document",
                "verbose_name_plural": "SAP Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SapDocumentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_num",
                    models.IntegerField(
                        default=0, help_text="Zero-based line number, as SAP expects"
                    ),
                ),
                ("item_code", models.CharField(max_length=50)),
                ("item_name", models.CharField(blank=True, default="", max_length=255)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Required by the invoice family, ignored by transfers",
                        max_digits=12,
                    ),
                ),
                (
                    "warehouse_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "base_entry",
                    models.IntegerField(
                        blank=True,
                        help_text="DocEntry of the document being reversed (returns)",
                        null=True,
                    ),
                ),
                (
                    "base_line",
                    models.IntegerField(
                        blank=True,
                        help_text="LineNum on the base document (returns)",
                        null=True,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sap_documents.sapdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAP Document Line",
                "verbose_name_plural": "SAP Document Lines",
                "ordering": ["line_num", "id"],
            },
        ),
        migrations.CreateModel(
            name="SapPostingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factory_used",
                    models.CharField(
                        help_text="Concrete factory class that built the payload",
                        max_length=100,
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        help_text="SAP Service Layer object posted to", max_length=100
                    ),
                ),
                ("succeeded", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True, default="")),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posting_logs",
                        to="sap_documents.sapdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "SAP Posting Log",
                "verbose_name_plural": "SAP Posting Logs",
                "ordering": ["-attempted_at"],
            },
        ),
    ]
